#%RAML 1.0
title: auth模块
mediaType: application/json
traits:
  secured: !include ../traits/secured.trait.raml
  dataError: !include ../traits/dataError.trait.raml
  serverError: !include ../traits/serverError.trait.raml
/auth:
  /login:
    post:
      description: 用户登录
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "username": { "type": "string", "description": "用户名" },
              "pwd": { "type": "string", "description": "密码" }
            }
          }
      responses:
        201:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "用户token"
                }
  /menus:
    get:
      description: 获取用户菜单列表
      is: [secured, serverError]
      queryParameters:
        name:
          description: 菜单名称
          type: string
          required: false
        description:
          description: 菜单描述
          type: string
          required: false
        route:
          description: 前端路径
          type: string
          required: false
        enable:
          description: 菜单状态(空为全部;Y为启用;N为停用)
          type: string
          required: false
      responses:
        200:
          body:
            text/plain:
              example: |
                {
                  "type": "array",
                    "properties": [
                      {
                        "id": { "type": "string", "description": "菜单ID" },
                        "icon": { "type": "string", "description": "菜单图标样式名称" },
                        "name": { "type": "string", "description": "菜单名称" },
                        "route": { "type": "string", "description": "前端路径" },
                        "enable": { "type": "boolean", "description": "菜单状态" },
                        "root": { "type": "boolean", "description": "是否为根节点" },
                        "identifier": { "type": "string", "description": "标识(预留字段)" },
                        "parentId": { "type": "string", "description": "父节点ID" },
                        "sequenceNumber": { "type": "integer", "description": "菜单同级排序号" },
                        "menuType": { "type": "object",  "properties": {
                          "code": { "type": "string", "description": "菜单类型编码" },
                          "name": { "type": "string", "description": "菜单类型名称" }
                          }
                        }
                      }
                    ]
                }
    post:
      description: 新增菜单
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "icon": { "type": "string", "description": "菜单图标样式名称" },
              "name": { "type": "string", "description": "菜单名称" },
              "route": { "type": "string", "description": "前端路径" },
              "enable": { "type": "boolean", "description": "菜单状态" },
              "parent": { "type": "object", "description": "父节点信息" },
              "sequenceNumber": { "type": "integer", "description": "菜单同级排序号" },
              "menuType": { "type": "object",  "properties": {
                "code": { "type": "string", "description": "菜单类型编码" },
                "name": { "type": "string", "description": "菜单类型名称" }
                }
              }
            }
          }
      responses:
        201:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "字符串"
                }
    put:
      description: 更新菜单列表的状态信息
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "enable": { "type": "boolean", "description": "菜单状态" },
              "ids": { "type": "array", "description": "string类型菜单ID列表" }
            }
          }
      responses:
        200:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "字符串"
                }
    delete:
      description: 删除多个菜单信息
      is: [secured, dataError, serverError]
      queryParameters:
        ids:
          description: 菜单信息Id列表(使用","分割)
          type: string
      responses:
        204:
        404:
    /{menuId}:
      get:
        description: 取得指定菜单ID详情信息
        is: [secured, serverError]
        responses:
          200:
            body:
              text/plain:
                example: |
                  {
                    "type": "object",
                    "properties": {
                      {
                        "id": { "type": "string", "description": "菜单ID" },
                        "icon": { "type": "string", "description": "菜单图标样式名称" },
                        "name": { "type": "string", "description": "菜单名称" },
                        "route": { "type": "string", "description": "前端路径" },
                        "enable": { "type": "boolean", "description": "菜单状态" },
                        "root": { "type": "boolean", "description": "是否为根节点" },
                        "identifier": { "type": "string", "description": "标识(预留字段)" },
                        "parentId": { "type": "string", "description": "父节点ID" },
                        "sequenceNumber": { "type": "integer", "description": "菜单同级排序号" },
                        "menuType": { "type": "object",  "properties": {
                          "code": { "type": "string", "description": "菜单类型编码" },
                          "name": { "type": "string", "description": "菜单类型名称" }
                        }
                      }
                     }
                    }
                  }
      put:
        description: 更新指定菜单ID的信息
        is: [secured, dataError, serverError]
        body:
          example: |
            {
              "type": "object",
              "properties": {
                "icon": { "type": "string", "description": "菜单图标样式名称" },
                "name": { "type": "string", "description": "菜单名称" },
                "route": { "type": "string", "description": "前端路径" },
                "enable": { "type": "boolean", "description": "菜单状态" },
                "parent": { "type": "object", "description": "父节点信息" },
                "sequenceNumber": { "type": "integer", "description": "菜单同级排序号" },
                "menuType": { "type": "object",  "properties": {
                  "code": { "type": "string", "description": "菜单类型编码" },
                  "name": { "type": "string", "description": "菜单类型名称" }
                }}
              }
            }
        responses:
          200:
            body:
              text/plain:
                example: |
                  {
                    "type": "string", "description": "字符串"
                  }
    /parents:
      get:
        description: 父节点菜单列表
        is: [secured, serverError]
        responses:
          200:
            body:
              text/plain:
                example: |
                  {
                    "type": "object",
                    "properties": {
                      "count": { "type": "long", "description": "数据数量" },
                      "data": { "type": "array", "properties": [
                        {
                          "id": { "type": "string", "description": "菜单ID" },
                          "icon": { "type": "string", "description": "菜单图标样式名称" },
                          "name": { "type": "string", "description": "菜单名称" },
                          "route": { "type": "string", "description": "前端路径" },
                          "enable": { "type": "boolean", "description": "菜单状态" },
                          "root": { "type": "boolean", "description": "是否为根节点" },
                          "identifier": { "type": "string", "description": "标识(预留字段)" },
                          "parentId": { "type": "string", "description": "父节点ID" },
                          "sequenceNumber": { "type": "integer", "description": "菜单同级排序号" },
                          "menuType": { "type": "object",  "properties": {
                            "code": { "type": "string", "description": "菜单类型编码" },
                            "name": { "type": "string", "description": "菜单类型名称" }
                           }}
                        }]
                      }
                    }
                  }
  /resources:
    post:
      description: 新增资源
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "name": { "type": "string", "description": "名称" },
              "url": { "type": "string", "description": "权限对应的Url地址" },
              "method": { "type": "string", "description": "请求方法" },
              "enable": { "type": "boolean", "description": "菜单状态" },
              "resourceType": { "type": "object",  "properties": {
                "code": { "type": "string", "description": "资源类型编码" },
                "name": { "type": "string", "description": "资源类型名称" }
              }
              }
            }
          }
      responses:
        201:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "字符串"
                }
    put:
      description: 更新资源列表的状态信息
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "enable": { "type": "boolean", "description": "资源状态" },
              "ids": { "type": "array", "description": "string类型资源ID列表" }
            }
          }
      responses:
        200:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "字符串"
                }
    delete:
      description: 删除多个资源信息
      is: [secured, dataError, serverError]
      queryParameters:
        ids:
          description: 资源信息Id列表(使用","分割)
          type: string
      responses:
        204:
        404:
    /{resourceId}:
      uriParameters:
        resourceId:
          description: 资源ID
          example: 1
      get:
        description: 取得指定用户ID的用户信息
        is: [secured, serverError]
        responses:
          200:
            body:
              example: |
                {
                  "type": "object",
                  "properties": {
                    "id": { "type": "string", "description": "资源 ID" },
                    "url": { "type": "string", "description": "资源 URL" },
                    "method": { "type": "string", "description": "资源 Method" },
                    "name": { "type": "string", "description": "资源名称" },
                    "enable": { "type": "boolean", "description": "菜单状态" },
                    "identifier": { "type": "string", "description": "标识(预留字段)" },
                    "resourceType": { "type": "object",  "properties": {
                      "code": { "type": "string", "description": "资源类型编码" },
                      "name": { "type": "string", "description": "资源类型名称" }
                    }},
                    "dataRestrainEntities": { "type": "array", "properties": [
                      {
                        "id": { "type": "string", "description": "数据约束 ID" },
                        "name": { "type": "string", "description": "数据约束名称" },
                        "tableName": { "type": "string", "description": "数据约束作用表名" },
                        "sqlStr": { "type": "string", "description": "数据约束具体 SQL" },
                        "filterName": { "type": "string", "description": "数据对象中定义的 Filter 名称" }
                      }]
                    },
                    "menuEntities": { "type": "array", "properties": [
                      {
                        "id": { "type": "string", "description": "菜单 ID" },
                        "name": { "type": "string", "description": "菜单名称" },
                        "route": { "type": "string", "description": "菜单对应的前端路径" },
                        "parent": { "type": "object", "description": "上级菜单" },
                        "parentId": { "type": "string", "description": "上级菜单 ID" },
                        "application": { "type": "object", "description": "菜单所属应用，即最上级的菜单" },
                        "root": { "type": "boolean", "description": "是否是根节点D" },
                        "leaf": { "type": "boolean", "description": "是否是叶子节点" },
                        "children": { "type": "array", "description": "子菜单集合" },
                        "resources": { "type": "array", "description": "菜单对应的资源集合" },
                        "sequenceNumber": { "type": "integer", "description": "菜单排序号（同一级别内）" },
                        "icon": { "type": "string", "description": "菜单图标样式名称" },
                        "roles": { "type": "array", "description": "拥有此菜单权限的角色集合" }
                      }]
                    }
                  }
                }
      put:
        description: 更新指定资源ID的资源信息
        is: [secured, dataError, serverError]
        body:
          example: |
            {
              "type": "object",
              "properties": {
                "name": { "type": "string", "description": "名称" },
                "url": { "type": "string", "description": "权限对应的Url地址" },
                "method": { "type": "string", "description": "请求方法" },
                "enable": { "type": "boolean", "description": "菜单状态" },
                "resourceType": { "type": "object",  "properties": {
                  "code": { "type": "string", "description": "资源类型编码" },
                  "name": { "type": "string", "description": "资源类型名称" }
                }}
              }
            }
        responses:
          200:
            body:
              text/plain:
                example: |
                  {
                    "type": "string", "description": "字符串"
                  }
      delete:
        description: 删除指定资源ID的资源信息
        is: [secured, dataError, serverError]
        responses:
          204:
          404:
  /users:
    post:
      description: 新增用户
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "username": { "type": "string", "description": "用户名" },
              "name": { "type": "string", "description": "显示名" },
              "password": { "type": "string", "description": "密码" },
              "email": { "type": "string", "description": "邮箱" },
              "phone": { "type": "string", "description": "手机号" },
              "valid": { "type": "boolean", "description": "是否有效" },
              "superuser": { "type": "boolean", "description": "是否为超级用户" }
            }
          }
      responses:
        201:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "字符串"
                }
    /{userId}:
      uriParameters:
        userId:
          description: 用户ID
          example: 1
      get:
        description: 取得指定用户ID的用户信息
        is: [secured, serverError]
        responses:
          200:
            body:
              example: |
                {
                  "type": "object",
                  "properties": {
                    "id": { "type": "string", "description": "用户ID" },
                    "username": { "type": "string", "description": "用户名" },
                    "password": { "type": "string", "description": "密码" },
                    "email": { "type": "string", "description": "邮箱" },
                    "superuser": { "type": "string", "description": "是否为超级用户" },
                    "userGroups": { "type": "array", "properties": [
                      {
                        "id": { "type": "string", "description": "用户组ID" },
                        "name": { "type": "string", "description": "用户组名称" },
                        "description": { "type": "string", "description": "用户组描述信息" },
                        "seq": { "type": "integer", "description": "顺序" },
                        "users": { "type": "array", "description": "用户组下用户集合" }
                      }
                    ] }
                  }
              }
      put:
        description: 更新指定用户ID的用户信息
        is: [secured, dataError, serverError]
        body:
          example: |
            {
              "type": "object",
              "properties": {
                "name": { "type": "string", "description": "名称" },
                "url": { "type": "string", "description": "权限对应的Url地址" },
                "method": { "type": "string", "description": "请求方法" }
              }
            }
        responses:
          200:
            body:
              text/plain:
                example: |
                  {
                    "type": "string", "description": "字符串"
                  }
      delete:
        description: 删除指定用户ID的用户信息
        is: [secured, dataError, serverError]
        responses:
          204:
          404:
  /user-groups:
    get:
      description: 取得全部有效的用户组信息
      is: [secured, serverError]
      responses:
        200:
          body:
            example: |
              {
                "type": "object",
                "properties": {
                  "name": { "type": "string", "description": "用户组名称" },
                  "description": { "type": "string", "description": "用户组描述信息" },
                  "seq": { "type": "integer", "description": "顺序" },
                  "users": { "type": "array", "properties": [
                    {
                      "username": { "type": "string", "description": "用户名" },
                      "password": { "type": "string", "description": "密码" },
                      "email": { "type": "string", "description": "邮箱" },
                      "superuser": { "type": "string", "description": "是否为超级用户" }
                    }
                  ] }
                }
              }
    post:
      description: 新增用户组
      is: [secured, dataError, serverError]
      body:
        example: |
          {
            "type": "object",
            "properties": {
              "name": { "type": "string", "description": "用户组名称" },
              "description": { "type": "string", "description": "用户组描述信息" },
              "seq": { "type": "integer", "description": "顺序" }
            }
          }
      responses:
        201:
          body:
            text/plain:
              example: |
                {
                  "type": "string", "description": "字符串"
                }
    /{id}:
      uriParameters:
        id:
          description: 用户组ID
          example: 1
      get:
        description: 取得指定用户组ID的用户组信息
        responses:
          200:
            body:
              example: |
                {
                  "type": "object",
                  "properties": {
                    "name": { "type": "string", "description": "用户组名称" },
                    "description": { "type": "string", "description": "用户组描述信息" },
                    "seq": { "type": "integer", "description": "顺序" },
                    "users": { "type": "array", "properties": [
                      {
                        "username": { "type": "string", "description": "用户名" },
                        "password": { "type": "string", "description": "密码" },
                        "email": { "type": "string", "description": "邮箱" },
                        "superuser": { "type": "string", "description": "是否为超级用户" }
                      }
                    ] }
                  }
                }
      put:
        description: 更新指定用户组ID的用户组信息
        is: [secured, dataError, serverError]
        body:
          example: |
            {
              "type": "object",
              "properties": {
                "name": { "type": "string", "description": "用户组名称" },
                "description": { "type": "string", "description": "用户组描述信息" },
                "seq": { "type": "integer", "description": "顺序" }
              }
            }
        responses:
          200:
            body:
              text/plain:
                example: |
                  {
                    "type": "string", "description": "字符串"
                  }
      delete:
        description: 删除指定用户组ID的用户组信息
        is: [secured, dataError, serverError]
        responses:
          204:
          404: