#%RAML 1.0
---
title: PEP auth API
baseUri: /sys/auth/security

securedBy: [JWTToken]
securitySchemes: !include ../pep-securitySchemes.raml
resourceTypes: !include ../pep-resourceTypes.raml
traits: !include ../pep-traits.raml

/resources:
  type:
    collection:
      exampleCollection: !include test.json
      exampleItem: !include test.json
  /{resourceId}:
    type:
      collection-item:
        exampleItem : !include test.json
