#%RAML 1.0 Trait
queryParameters:
  pageNo:
    description: 分页页码
    type: integer
    required: true
    example: 6
    default: 1
  pageSize:
    description: 分页大小
    type: integer
    required: true
    example: 80
    default: 10