#%RAML 1.0 DataType
type: object
properties:
  icon:
    description: 菜单图标样式名称
    required: true
    type: string
  name:
    description: 菜单名称
    required: true
    type: string
  route:
    description: 前端路径
    required: true
    type: string
  enable:
    description: 菜单状态
    required: true
    type: boolean
  parentId:
    description: 父节点ID
    required: true
    type: string
  sequenceNumber:
    description: 菜单同级排序号
    required: true
    type: integer
  menuCode:
    description: 菜单类型编码(0:应用/1:页面/2:功能)
    required: true
    type: string
example:
  icon: "icon"
  name: 菜单
  route: /menu/resource
  enable: true
  parentId: "parentId"
  sequenceNumber: 1
  menuCode: "1"